sonar.projectKey=Akasam_todo-api-python-test
sonar.organization=akasam
sonar.projectName=todo-api-python-test

sonar.sources=.
sonar.exclusions=tests/**,htmlcov/**
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml

sonar.python.version=3.11
